"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useReducer } from "react";
import "./globals.css";
import layoutContext from "@/contexts/layoutContext";
import { hasAuthToken } from "@/helpers/authHelper";
const inter = Inter({ subsets: ["latin"] });
import dynamic from 'next/dynamic'

const Header = dynamic(() => import('../components/header'), { ssr: false })
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const layoutReducer = (state = {}, action : any ) => {
    switch (action.type) {
      case "SET_LOGIN_STATUS":
        state = { ...state, login_status: action.payload };
        return state;
      default:
        return state;
    }
  };

  const [layoutState, layoutDispatch] = useReducer(layoutReducer, {
    login_status: hasAuthToken(),
  });
  const providerState = {
    layoutState,
    layoutDispatch,
  };

  // console.log(hasAuthToken());
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <layoutContext.Provider value={providerState}>
          <Header />
          {children}
        </layoutContext.Provider>
      </body>
    </html>
  );
}
