"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useReducer } from "react";
import "./globals.css";
import Header from "../app/components/header";
import layoutContext from "./contexts/layoutContext";
import { hasAuthToken } from "@/app/helpers/authHelper";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const layoutReducer = (state = {}, action) => {
    switch (action.type) {
      case "SET_LOGIN_STATUS":
        state = { ...state, login_status: action.payload };
        return state;
      default:
        return state;
    }
  };

  const [layoutState, layoutDispatch] = useReducer(layoutReducer, {
    login_status: hasAuthToken(),
  });
  const providerState = {
    layoutState,
    layoutDispatch,
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <layoutContext.Provider value={providerState}>
          <Header />
          {children}
        </layoutContext.Provider>
      </body>
    </html>
  );
}
